project:
  type: website
  output-dir: docs
  resources:
    - data/*


website:
  title: "EDA de Práctica"
  site-url: "https://jorgedelgado13.github.io/practica_ml/"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    toc: true

execute:
  echo: true
  warning: false
  message: false
freeze: auto

